import 'package:flutter/material.dart';
import 'package:reactive_forms/reactive_forms.dart';
//import 'package:flutter/services.dart';

class SourcingPage extends StatelessWidget {
  final String title;

  SourcingPage(String s, {required this.title, Key? key}) : super(key: key);

  final form = FormGroup({
    'businessdescription': FormControl<String>(validators: [Validators.required]),
    'sourcingchannel': FormControl<String>(validators: [Validators.required]),
    'sourcingid': FormControl<String>(validators: [Validators.required]),
    'sourcingname': FormControl<String>(validators: [Validators.required]),
    'preferredbranch': FormControl<String>(validators: [Validators.required]),
    'branchcode': FormControl<String>(validators: [Validators.required]),
    'leadgeneratedby': FormControl<String>(validators: [Validators.required]),
    'leadid': FormControl<String>(validators: [Validators.required]),
    'customername': FormControl<String>(validators: [Validators.required]),
    'dateofbirth': FormControl<String>(validators: [Validators.required]),
    'mobilenumber': FormControl<String>(validators: [Validators.required]),
    'productinterest': FormControl<String>(validators: [Validators.required]),
  });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
    appBar: AppBar(
      title: Text("Sourcing Details"),
       ),
      body: ReactiveForm(
        formGroup: form,
        child: SingleChildScrollView(
          child: Column(
            children: [
              _buildDropdown(
                controlName: 'businessdescription',
                label: 'Business Description',
                items: ['MSME', 'Retail'],
              ),
              _buildDropdown(
                controlName: 'sourcingchannel',
                label: 'Sourcing Channel',
                items: ['Direct Call', 'Lead Management System', 'Online', 'Partner', 'Website'],
              ),
              _buildTextField('sourcingid', 'Sourcing ID'),
              _buildTextField('sourcingname', 'Sourcing Name'),
              _buildDropdown(
                controlName: 'preferredbranch',
                label: 'Preferred Branch',
                items: ['AMTA', 'ASHOKENAGAR', 'BAGMORE'],
              ),
              _buildTextField('branchcode', 'Branch Code'),
              _buildTextField('leadgeneratedby', 'Lead Generated By'),
              _buildTextField('leadid', 'Lead ID'),
              _buildTextField('customername', 'Customer Name'),
              _buildTextField('dateofbirth', 'Date Of Birth'),
              _buildTextField('mobilenumber', 'Mobile Number'),
              _buildDropdown(
                controlName: 'productinterest',
                label: 'Product Interest',
                items: ['Loan', 'Credit Card', 'Insurance'],
              ),
              SizedBox(height: 20),
              Center(
                child: ElevatedButton(
                  onPressed: () {
                  },
                  child: Text('Next'),
                ),
              ),
              SizedBox(height: 20),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildDropdown({
    required String controlName,
    required String label,
    required List<String> items,
  }) {
    return Padding(
      padding: EdgeInsets.all(16),
      child: ReactiveDropdownField<String>(
        formControlName: controlName,
        decoration: InputDecoration(
          labelText: label,
          hintText: '--Select--',
        ),
        items: items
            .map((e) => DropdownMenuItem<String>(
                  value: e,
                  child: Text(e),
                ))
            .toList(),
      ),
    );
  }

  Widget _buildTextField(String controlName, String label) {
    return Padding(
      padding: const EdgeInsets.all(16),
      child: ReactiveTextField<String>(
        formControlName: controlName,
        //  keyboardType: controlName == 'mobilenumber' ? TextInputType.number : TextInputType.text,
        //  inputFormatters: controlName == 'mobilenumber'
        //   ? [FilteringTextInputFormatter.digitsOnly]
        //   : [],
        decoration: InputDecoration(
          labelText: label,
        ),
      ),
    );
  }
}

