import 'package:flutter/material.dart';
import 'package:reactive_forms/reactive_forms.dart';
import 'package:flutter/services.dart';

class SourcingPage extends StatelessWidget {
  final String title;

  SourcingPage(String s, {required this.title, Key? key}) : super(key: key);

  final form = FormGroup({
    'businessdescription': FormControl<String>(validators: [Validators.required]),
    'sourcingchannel': FormControl<String>(validators: [Validators.required]),
    'sourcingid': FormControl<String>(validators: [Validators.required]),
    'sourcingname': FormControl<String>(validators: [Validators.required]),
    'preferredbranch': FormControl<String>(validators: [Validators.required]),
    'branchcode': FormControl<String>(validators: [Validators.required]),
    'leadgeneratedby': FormControl<String>(validators: [Validators.required]),
    'leadid': FormControl<String>(validators: [Validators.required]),
    'customername': FormControl<String>(validators: [Validators.required]),
    'dateofbirth': FormControl<String>(validators: [Validators.required]),
    'mobilenumber': FormControl<String>(validators: [Validators.required]),
    'productinterest': FormControl<String>(validators: [Validators.required]),
  });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Sourcing Details"),
      ),
      body: ReactiveForm(
        formGroup: form,
        child: SingleChildScrollView(
          child: Column(
            children: [
              Dropdown(
                controlName: 'businessdescription',
                label: 'Business Description',
                items: ['MSME', 'Retail'],
              ),
              Dropdown(
                controlName: 'sourcingchannel',
                label: 'Sourcing Channel',
                items: ['Direct Call', 'Lead Management System', 'Online', 'Partner', 'Website'],
              ),
              IntegerTextField('sourcingid', 'Sourcing ID'),
              TextField('sourcingname', 'Sourcing Name'),
              Dropdown(
                controlName: 'preferredbranch',
                label: 'Preferred Branch',
                items: ['AMTA', 'ASHOKENAGAR', 'BADU', 'BAGMORE', 
                'BAGNAN', 'BAGUIATI-KOLKATA', 'BAKSHARA-HOWRAH', 
                'BAKULTALA', 'BALLY GOSWAMIPARA', 'BALTIKURI-HOWRAH', 
                'BAMUNGACHI', 'BANIPUR', 'BANITABLA', 'BANKRA-HOWRAH', 
                'BARASAT', 'BARGACHIA', 'BEGRI', 'BELGHARIA', 'BELIAGHATA BRIDGE',
                'BELLILIOUS ROAD', 'BESU', 'BINDHANNAGAR', 'BILKANDA', 'BONGAON', 
                'CHANDPORE', 'DAKSHIN JHAPARDA', 'DAKSHIN JOYPUR', 'DAKSHINESWAR', 
                'DUM DUM-KOLKATA', 'GARIA-KOLKATA', 'HABRA', ],
              ),
              IntegerTextField('branchcode', 'Branch Code'),
              IntegerTextField('leadgeneratedby', 'Lead Generated By'),
              IntegerTextField('leadid', 'Lead ID'),
              TextField('customername', 'Customer Name'),
              TextField('dateofbirth', 'Date Of Birth'),
              IntegerTextField('mobilenumber', 'Mobile Number'),
              Dropdown(
                controlName: 'productinterest',
                label: 'Product Interest',
                items: ['Car Loan', 'Cash Loan', 'Combo Car Loan', 
                'Corporate Car Loan', 'Corporate Home Loan', 
                'Educational Loan', 'Housing Loan', 'Pensioner Loan', 
                'Property Loan', 'Rent Loan', 'UCO Survodaya Loan Scheme', 
                'Two Wheeler Loan', 'UCO Electric Vehicle Loan', 
                'UCO Electric Vehicle EV Loan', 'UCO Elite Two Wheeler Loan' ],
              ),
              SizedBox(height: 20),
              Center(
                child: ElevatedButton(
                  onPressed: () {
                    if (form.valid) {
                      final tabController = DefaultTabController.of(context);
                      if (tabController.index < tabController.length - 1) {
                        tabController.animateTo(tabController.index + 1);
                      }
                    } else {
                      form.markAllAsTouched();
                    }
                  },
                  child: Text('Next'),
                ),
              ),
              SizedBox(height: 20),
            ],
          ),
        ),
      ),
    );
  }

  Widget Dropdown({
    required String controlName,
    required String label,
    required List<String> items,
  }) {
    return Padding(
      padding: EdgeInsets.all(16),
      child: ReactiveDropdownField<String>(
        formControlName: controlName,
        decoration: InputDecoration(
          labelText: label,
          hintText: '--Select--',
        ),
        items: items
            .map((e) => DropdownMenuItem<String>(
                  value: e,
                  child: Text(e),
                ))
            .toList(),
      ),
    );
  }

  Widget TextField(String controlName, String label) {
    return Padding(
      padding: const EdgeInsets.all(16),
      child: ReactiveTextField<String>(
        formControlName: controlName,
        decoration: InputDecoration(
          labelText: label,
        ),
      ),
    );
  }

  Widget IntegerTextField(String controlName, String label) {
    return Padding(
      padding: const EdgeInsets.all(16),
      child: ReactiveTextField<String>(
        formControlName: controlName,
        keyboardType: TextInputType.number,
        inputFormatters: [
          FilteringTextInputFormatter.digitsOnly,
        ],
        decoration: InputDecoration(
          labelText: label,
        ),
      ),
    );
  }
}
